app_settings:
  port: 8000
  stylesheet: lumen
  enable_logging: false
  logging_level: warning
  log_to_file: false
  variableselector:
    ident: orgnr
    time_units:
      name: aar
      frequency: year
modules: # Here you can add more modules and tailor your app to your needs.
  tabs:
    - type: DataEditor
