// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table kontaktinfo {
  id int [pk, increment]
  iso_period varchar
  skjema varchar
  ident varchar
  refnr varchar
  kontaktperson varchar
  epost varchar
  telefon varchar
  bekreftet_kontaktinfo varchar
  kommentar_kontaktinfo varchar
  kommentar_krevende varchar
}

Table enheter {
  id int [pk, increment]
  iso_period varchar
  skjema varchar
  ident varchar
}

Table skjemamottak {
  id int [pk, increment]
  iso_period varchar
  start_date timestamp
  end_date timestamp
  skjema varchar
  skjema_versjon varchar [null]
  ident varchar
  refnr varchar
  kommentar varchar
  dato_mottatt timestamp
  status varchar
  aktiv boolean
}

Table enhetsinfo {
  id int [pk, increment]
  iso_period varchar
  ident varchar
  variable varchar
  verdi varchar
}

Table skjemadata {
  id int [pk, increment]
  iso_period varchar
  skjema varchar
  ident varchar
  refnr varchar
  feltsti varchar [null]
  feltnavn varchar
  verdi varchar [null]
  alias varchar [null]
  dybde int [null]
  indeks int [null]
}

Ref: "enheter"."iso_period" < "skjemamottak"."iso_period"

Ref: "enheter"."ident" < "skjemamottak"."ident"

Ref: "enheter"."skjema" < "skjemamottak"."skjema"

Ref: "enheter"."iso_period" < "enhetsinfo"."iso_period"

Ref: "enheter"."ident" < "enhetsinfo"."ident"

Ref: "skjemamottak"."refnr" < "skjemadata"."refnr"

Ref: "skjemamottak"."ident" < "skjemadata"."ident"

Ref: "skjemamottak"."skjema" < "skjemadata"."skjema"

Ref: "skjemamottak"."iso_period" < "skjemadata"."iso_period"

Ref: "skjemamottak"."iso_period" < "kontaktinfo"."iso_period"

Ref: "skjemamottak"."skjema" < "kontaktinfo"."skjema"

Ref: "skjemamottak"."ident" < "kontaktinfo"."ident"

Ref: "skjemamottak"."refnr" < "kontaktinfo"."refnr"
