services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpwd
      POSTGRES_DB: devdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  python-container:
    image: mcr.microsoft.com/devcontainers/python:3.12
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: dev
      DB_PASSWORD: devpwd
      DB_NAME: devdb

volumes:
  postgres-data:
